### ISSUE TITLE
What's the current state of the PASETO RFC?

### ISSUE THREAD

**Issue by jovial-snyder** [paseto-standard/paseto-rfc#2]
AFAIK this is the current draft: https://github.com/paseto-standard/paseto-rfc/blob/master/draft-paragon-paseto-rfc-01.txt
So it had the status **Informational** since it's release early in April 2018. Are there any plans to continue working on it, or is the project abandoned? Sadly there is very little information on https://paseto.io.

**Comment by paragonie-security** [comment]
No, it's not the current draft. We're working on adding PASETO v3/v4 to the current RFC draft text.

**Comment by paragonie-security** [comment]
(For the time being, feel free to disregard the IETF's opinion and focus instead on what makes good sense for the security and interoperability of your systems. If you can find an implementation of PASETO in every language you care about, why does a standards organization's opinion matter?)
