### ISSUE TITLE
Why DtTime instad of NumericDate for 'exp', 'nbf', 'iat'?

### ISSUE THREAD

**Issue by foriequal0** [paseto-standard/paseto-rfc#4]
JWT RFC 7519 requires those claims contain a number containing a NumericDate value.
https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.6

But the current PASETO RFC draft requires those claims to be DtTime.
https://github.com/paseto-standard/paseto-rfc/blob/master/draft-paragon-paseto-rfc-01.txt#L1083-L1116

Any reasons for this?

**Comment by paragonie-security** [comment]
https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by foriequal0** [comment]
Isn't it only applied for 32bit representation?
We can safely use up to 53bit in JSON in general.
I think we don't have to worry about year 285,428,987 problem for a while.

**Comment by paragonie-security** [comment]
We're not constrained by JWT's mistakes, and ISO 8601 is preferable to UNIX timestamps because it encodes timezone information.
